"""empty message

Revision ID: 2008450e4dc7
Revises: 
Create Date: 2025-05-03 14:25:16.821668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2008450e4dc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_type', sa.String(length=100), nullable=False),
    sa.Column('practitioner_name', sa.String(length=100), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('starting_time', sa.Time(), nullable=False),
    sa.Column('ending_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('provider_number', sa.Integer(), nullable=True),
    sa.Column('appointment_type', sa.String(length=100), nullable=False),
    sa.Column('appointment_notes', sa.String(length=1000), nullable=False),
    sa.Column('custom_reminder', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=200), nullable=False),
    sa.Column('document_name', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_notes', sa.String(length=1000), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('user_profiles')
    op.drop_table('appointments')
    op.drop_table('users')
    # ### end Alembic commands ###
