"""Add reminder field to Appointment model

Revision ID: 273800b28a74
Revises: 411d6603cd44
Create Date: 2025-05-03 16:09:23.346922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273800b28a74'
down_revision = '411d6603cd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('reminder')

    # ### end Alembic commands ###
