"""Make custom_reminder nullable

Revision ID: 6e9a4b232e24
Revises: 3fd41951b5ed
Create Date: 2025-05-04 18:09:27.609246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9a4b232e24'
down_revision = '3fd41951b5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('custom_reminder',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('custom_reminder',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
