"""Add temp_flag to User

Revision ID: 75271ee604f6
Revises: db11a3d7371e
Create Date: 2025-05-16 18:52:52.980849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75271ee604f6'
down_revision = 'db11a3d7371e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temp_flag')

    # ### end Alembic commands ###
